"""create print_estimates and pricing_rates tables

Revision ID: 4b93572352e9
Revises: 
Create Date: 2026-09-02 20:47:53.734957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b93572352e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('color_mode', sa.String(length=10), nullable=False),
    sa.Column('print_type', sa.String(length=10), nullable=False),
    sa.Column('price_per_printed_side', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rates_id'), 'pricing_rates', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_rates_key'), 'pricing_rates', ['key'], unique=True)
    op.create_table('print_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('copies', sa.Integer(), nullable=False),
    sa.Column('color_mode', sa.String(length=10), nullable=False),
    sa.Column('print_type', sa.String(length=10), nullable=False),
    sa.Column('price_per_printed_side', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('printed_sides_per_copy', sa.Integer(), nullable=False),
    sa.Column('physical_sheets_per_copy', sa.Integer(), nullable=False),
    sa.Column('total_printed_sides', sa.Integer(), nullable=False),
    sa.Column('total_physical_sheets', sa.Integer(), nullable=False),
    sa.Column('cost_per_copy', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_estimates_id'), 'print_estimates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_print_estimates_id'), table_name='print_estimates')
    op.drop_table('print_estimates')
    op.drop_index(op.f('ix_pricing_rates_key'), table_name='pricing_rates')
    op.drop_index(op.f('ix_pricing_rates_id'), table_name='pricing_rates')
    op.drop_table('pricing_rates')
    # ### end Alembic commands ###
